'use strict';
function answerCoveragePanel(){const bank=BANK.filter(q=>homeExam==='all'||q.exam===homeExam),m=PYQAnswers.coverage(bank),segments=[['Official keys',m.official,'var(--blue)'],['Derived answers',m.solved,'var(--lime)'],['Book keys',m.book,'var(--orange)'],['Written references',m.written,'var(--purple)'],['Source issues',m.issues,'var(--danger)']];return `<section class="panel answer-coverage"><div class="section-head"><div><div class="eyebrow">ANSWER LIBRARY / ${homeExam==='all'?'ALL TRACKS':esc(TRACKS[homeExam].short)}</div><h3>Check every question.</h3><p>${num(m.keyed)} automatically gradable · ${num(m.written)} written references · ${m.issues} explained source issues</p></div><button data-view="bank">Explore answers ↗</button></div><div class="answer-coverage-bar" aria-label="Answer reference coverage">${segments.filter(x=>x[1]).map(([label,n,color])=>`<i style="width:${n/Math.max(1,m.total)*100}%;background:${color}" title="${label}: ${n}"></i>`).join('')}</div><div class="answer-coverage-legend">${segments.map(([label,n,color])=>`<span><i style="background:${color}"></i>${label}<b>${num(n)}</b></span>`).join('')}</div><p class="chart-note">Derived answers and Mains references are independently worked, not official marking schemes. Source issues have a checking note and are excluded from automatic scores.</p></section>`}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.resultAnswer&&state.session?.finished){const q=qData(b.dataset.resultAnswer);showModal('Answer reference',feedback(q,state.session.answers[q.id]))}if(b.dataset.selfReview){if(state.session?.mode==='exam'&&!state.session.finished)return;selfReview(b.dataset.selfReview)}});

function recheckSavedAnswers(){
 const plan=PYQRecheck.preview(state.attempts,BANK.map(q=>qData(q.id)));
 showModal('Recheck saved objective answers',`<p>${plan.changes.length} saved results can be updated with the current keys. ${plan.newlyGraded} previously ungraded responses can receive a score. ${plan.needsRetry} responses need a fresh attempt because their answer format changed.</p><p>Your responses, dates, working notes and written self-scores are preserved. Original grades are kept in the exported backup history. Revision schedules are not advanced by rechecking.</p><div class="form-actions"><button id="confirm-recheck" class="primary" ${plan.changes.length?'':'disabled'}>Update saved results</button><button data-close>Cancel</button></div>`);
 $('#confirm-recheck').onclick=()=>{state.attempts=PYQRecheck.apply(state.attempts,plan);save();modal.close();render();toast(`${plan.changes.length} saved results updated; original grades preserved.`)};
}
