'use strict';
let subjectSearch='',subjectGroup='all',subjectAvailability='all';
const subjectInfo=id=>PYQCatalog.subjects.find(s=>s.id===id);
const scopeBank=()=>PYQCatalog.inScope(BANK,state.subject||'all');
const scopeAttempts=()=>{const ids=new Set(scopeBank().map(q=>q.id));return state.attempts.filter(a=>ids.has(a.id))};
const subjectName=id=>subjectInfo(id)?.name||'All subjects';
function resetFilters(){filter={exam:'all',type:'all',chapter:'all',year:'all',status:'all',search:''};page=0}
function setSubject(id,open=false){if(id!=='all'&&!subjectInfo(id))return;state.subject=id;save();resetFilters();navigate(id==='all'&&view==='subject'?'subjects':open||view==='dashboard'||view==='subject'?'subject':view)}
function summaryFor(id='all'){return PYQCatalog.summary(BANK,state.attempts,id)}
function subjectCard(s){const m=summaryFor(s.id),pct=m.total?Math.round(m.attempted/m.total*100):0;return `<button class="subject-card ${m.total?'available':'planned'}" data-subject="${s.id}" style="--subject-color:${s.color}"><div class="subject-card-top"><span class="subject-symbol">${s.icon}</span><span class="availability ${m.total?'ready':''}">${m.total?'● Ready to practise':'Awaiting question bank'}</span></div><small class="subject-group">${esc(s.group)}</small><h3>${esc(s.name)}</h3><p>${esc(s.description)}</p><div class="subject-card-bottom"><span>${m.total?`${num(m.total)} questions · ${pct}% practised`:'Set up for future integration'}</span><span>↗</span></div>${m.total?`<div class="subject-progress"><i style="width:${pct}%"></i></div>`:''}</button>`}
function subjectsView(){return `${header('Your subject universe.','A single home for every question bank. Open a subject to see its chapters, coverage and next steps.','SUBJECT HUB')}<div class="hub-toolbar"><input type="search" id="subject-search" placeholder="Find a subject…" aria-label="Search subjects" value="${esc(subjectSearch)}"><select id="subject-group" aria-label="Subject group"><option value="all">Every discipline</option>${[...new Set(PYQCatalog.subjects.map(s=>s.group))].map(g=>`<option ${subjectGroup===g?'selected':''}>${esc(g)}</option>`).join('')}</select><select id="subject-availability" aria-label="Subject availability"><option value="all">All subjects</option><option value="ready" ${subjectAvailability==='ready'?'selected':''}>Ready to practise</option><option value="planned" ${subjectAvailability==='planned'?'selected':''}>Awaiting question banks</option></select></div><div class="hub-note">SOM is available now. Other subjects have dedicated spaces and will become practice-ready when their question banks are integrated.</div><div id="subject-grid" class="subject-grid">${subjectGrid()}</div>`}
function subjectGrid(){const rows=PYQCatalog.subjects.filter(s=>(subjectGroup==='all'||s.group===subjectGroup)&&`${s.name} ${s.short} ${s.group}`.toLowerCase().includes(subjectSearch.toLowerCase())&&(subjectAvailability==='all'||(subjectAvailability==='ready')===!!summaryFor(s.id).total));return rows.length?rows.map(subjectCard).join(''):'<div class="panel empty">No subjects match. Try another name or filter.</div>'}
function subjectWorkspace(){const s=subjectInfo(state.subject);if(!s)return subjectsView();const qs=scopeBank(),m=summaryFor(s.id),done=tracked(),chapters=[...new Set(qs.map(q=>q.chapter))];return `${header(esc(s.name),esc(s.description),`${esc(s.group).toUpperCase()} / SUBJECT WORKSPACE`)}<div class="subject-banner" style="--subject-color:${s.color}"><span class="subject-symbol">${s.icon}</span><div><strong>${m.total?'Your subject, in focus.':'A dedicated space, ready to grow.'}</strong><p>${m.total?'Practice, notes, revision and results are connected to this subject.':'No question bank has been uploaded for this subject yet. No sample questions or scores are shown.'}</p></div><button class="${m.total?'primary':'secondary'}" ${m.total?'data-action="quick"':'data-plan-subject="'+s.id+'"'}>${m.total?'Practise this subject ↗':'Add to study plan'}</button></div>${m.total?`<div class="stats">${stat('Question entries',num(m.total),`${chapters.length} chapters`)}${stat('Ready to grade',num(m.keyed),'Keys with reliable marks')}${stat('Practised',m.attempted,`${Math.round(m.attempted/m.total*100)}% explored`)}${stat('Accuracy',m.graded?Math.round(m.correct/m.graded*100)+'%':'—','Graded responses only')}</div><div class="section-head"><h2>Exam tracks</h2><button class="text-btn" data-view="mock">Build a test ↗</button></div><div class="tracks">${Object.entries(TRACKS).filter(([id])=>qs.some(q=>q.exam===id)).map(([id,t])=>`<article class="track" style="--accent:${t.color}"><div class="track-icon">${t.icon}</div><h3>${t.name}</h3><p>${qs.filter(q=>q.exam===id).length} questions</p><button data-track="${id}">Open track ↗</button></article>`).join('')}</div><section class="panel"><div class="section-head"><h2>Chapter map</h2><button class="text-btn" data-view="bank">Question library ↗</button></div>${chapters.map((ch,i)=>{const rows=qs.filter(q=>q.chapter===ch),count=rows.filter(q=>done.has(q.id)).length;return `<div class="chapter-row"><span class="chapter-index">${String(i+1).padStart(2,'0')}</span><div class="chapter-name">${esc(ch)}<small>${count} / ${rows.length} practised</small></div><div class="mini-progress"><i style="width:${count/rows.length*100}%"></i></div><button class="text-btn" data-chapter="${esc(ch)}" aria-label="Practise ${esc(ch)}">↗</button></div>`}).join('')}</section>`:`<div class="lower-grid"><section class="panel"><h3>What will live here</h3><div class="coverage"><p>Original question screenshots, chapter filters and source references.</p><p>GATE answer controls and ESE practice modes for the supplied papers.</p><p>Saved notes, bookmarks, timed tests and subject progress.</p></div></section><section class="panel"><h3>Keep building your preparation</h3><p class="muted">Plan this subject now, or practise from an available question bank.</p><div class="form-actions"><button data-view="subjects">Choose another subject</button></div></section></div>`}`}
function planRow(t){const s=subjectInfo(t.subject);return `<div class="plan-row ${t.done?'done':''}"><button data-plan-toggle="${esc(t.id)}" aria-label="${t.done?'Mark incomplete':'Complete'}: ${esc(t.title)}" aria-pressed="${!!t.done}">${t.done?'✓':'○'}</button><div><strong>${esc(t.title)}</strong><small>${esc(s?.name||'All subjects')} · ${esc(t.date)} · ${Number(t.minutes)} min${!t.done&&t.date<today()?' · Overdue':''}</small></div><button class="text-btn" data-plan-remove="${esc(t.id)}" aria-label="Remove study block ${esc(t.title)}">×</button></div>`}
function today(){const d=new Date;return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function plannerView(){const rows=[...(state.planner||[])].sort((a,b)=>Number(a.done)-Number(b.done)||a.date.localeCompare(b.date));return `${header('Make consistency a plan.','A subject-by-subject study plan, saved with your workspace.','STUDY PLANNER')}<div class="lower-grid"><section class="panel"><h2>Plan a focused block</h2><form id="planner-form" class="planner-form"><label class="field">Subject<select name="subject">${PYQCatalog.subjects.map(s=>`<option value="${s.id}" ${state.subject===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label class="field">Your focus<input name="title" required maxlength="100" placeholder="e.g. Revise beam bending and practise 10 PYQs"></label><div class="form-grid"><label class="field">Date<input type="date" name="date" value="${today()}" required></label><label class="field">Minutes<input type="number" name="minutes" min="5" max="480" value="30" required></label></div><button class="primary" type="submit">Add study block +</button><p class="muted">Planning only: no notifications or reminders are sent.</p></form></section><section class="panel"><div class="section-head"><h3>Your study blocks</h3><span class="badge">${rows.filter(t=>t.done).length} / ${rows.length} complete</span></div>${rows.length?rows.map(planRow).join(''):'<div class="empty">Your next study block starts with a small, specific target.</div>'}</section></div>`}
function subjectAnalytics(){return `<section class="panel subject-analytics"><div class="section-head"><h3>Progress across subjects</h3><span class="muted">Practised / available</span></div>${PYQCatalog.subjects.filter(s=>summaryFor(s.id).total).map(s=>{const m=summaryFor(s.id);return `<div class="chapter-row"><span class="subject-symbol small">${s.icon}</span><div class="chapter-name">${esc(s.name)}<small>${m.attempted} / ${m.total} questions · ${m.graded?Math.round(m.correct/m.graded*100)+'% graded accuracy':'No graded attempts'}</small></div><div class="mini-progress"><i style="width:${m.attempted/m.total*100}%"></i></div><button class="text-btn" data-subject="${s.id}">↗</button></div>`}).join('')}</section>`}
function searchWorkspace(){showModal('Find your next step',`<input id="global-search" type="search" class="global-search" aria-label="Search the workspace" placeholder="Search subjects, chapters or questions…"><div id="global-results"></div><p>Search spans all subjects, regardless of your current subject filter.</p>`);const update=()=>{const term=$('#global-search').value.trim().toLowerCase();const ss=PYQCatalog.subjects.filter(s=>`${s.name} ${s.short}`.toLowerCase().includes(term)).slice(0,5);const qs=term.length>1?BANK.filter(q=>`${q.title} ${q.chapter} ${q.text||''}`.toLowerCase().includes(term)).slice(0,7):[];$('#global-results').innerHTML=ss.map(s=>`<button class="search-result" data-subject="${s.id}" data-close><span>${s.icon} ${esc(s.name)}</span><small>${summaryFor(s.id).total?'Subject workspace':'Awaiting question bank'}</small></button>`).join('')+qs.map(q=>`<button class="search-result" data-open="${esc(q.id)}" data-close><span>${esc(q.title)}</span><small>${esc(subjectName(q.subject))} · ${esc(q.chapter)}</small></button>`).join('')+(!ss.length&&!qs.length?'<p>No matches. Try another topic or question number.</p>':'')};$('#global-search').oninput=update;update();$('#global-search').focus()}
function bindPlatform(){
  const scope=$('#subject-scope');scope.innerHTML=`<option value="all">All subjects</option>${PYQCatalog.subjects.map(s=>`<option value="${s.id}" ${state.subject===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}`;scope.onchange=e=>setSubject(e.target.value);
  if($('#subject-search'))$('#subject-search').oninput=e=>{subjectSearch=e.target.value;$('#subject-grid').innerHTML=subjectGrid()};
  for(const [id,set]of [['subject-group',v=>subjectGroup=v],['subject-availability',v=>subjectAvailability=v]])if($('#'+id))$('#'+id).onchange=e=>{set(e.target.value);$('#subject-grid').innerHTML=subjectGrid()};
  if($('#planner-form'))$('#planner-form').onsubmit=e=>{e.preventDefault();const f=new FormData(e.target),title=String(f.get('title')).trim();if(!title)return;state.planner||=[];state.planner.push({id:'plan-'+Date.now()+'-'+Math.random().toString(36).slice(2,8),subject:f.get('subject'),title,date:f.get('date'),minutes:Number(f.get('minutes')),done:false});save();render();toast('Study block added')};
}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.subject)setSubject(b.dataset.subject,true);if(b.dataset.planSubject){state.subject=b.dataset.planSubject;save();navigate('planner')}if(b.dataset.planToggle){const t=(state.planner||[]).find(t=>t.id===b.dataset.planToggle);if(t){t.done=!t.done;save();render()}}if(b.dataset.planRemove){state.planner=(state.planner||[]).filter(t=>t.id!==b.dataset.planRemove);save();render()}if(b.id==='workspace-search')searchWorkspace()});
document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();if(!modal.open)searchWorkspace()}});
